### ISSUE TITLE
Finish transition from Ant to Bach.java

### ISSUE THREAD

**Issue by sormuras** [jbee/purejin#82]
With #80 being merged - wohoo! -- these are some pending tasks:

### Tasks

- [x] Provide JitPack configuration file prior to uploading to Maven Central? (https://jitpack.io/#jbee/silk)
- [x] Copy Maven-related consumer parts from Ant's `build.xml` into a dedicated file (similar to https://github.com/sormuras/bach/blob/master/src/de.sormuras.bach/main/maven/pom.xml)
- [x] Get modular `javadoc` running -- follow up to #83 
- [x] Compile for JVM version 8
- [x] Cleanup modular JAR contents (e.g., remove redundant `META-INF/versions/9` directory)
- [ ] Code Coverage

### Nice-To-Have

- [x] Move Java source files into a Jigsaw-friendly directory tree structure. The convention is described here: https://openjdk.java.net/projects/jigsaw/quick-start by _"By convention, the source code for the module is in a directory that is the name of the module"_.

From
```
├───core
...
├───core-module
├───example
│   ├───com
│   │   └───example
│   │       └───app
│   └───META-INF
│       └───services
├───example-module
│   └───com
│       └───example
│           └───test
├───test
│   └───se
│       └───jbee
│           └───inject
│               ├───action
│               ├───bind
│               ├───container
│               ├───convert
│               ├───event
│               ├───scope
│               └───util
└───test-module
```
to
```
src\se.jbee.inject\
src\se.jbee.inject\main\java
src\se.jbee.inject\test\java
src\com.example\test\java
src\test\test\java
```

**Comment by jbee** [comment]
I had a quick look at the ant build file. As far as I can tell there is nothing particularly important in it (any longer). Assuming we can compile and run tests we have most of it covered. There are only two further things done:

* get jar file published to maven central (broken I think)
* out copyright header in files

I think the publishing can be done in any way convenient. E.g. JitPack

Copyright headers are not very important to me. In the long run it would be nice if bach can do that for us.

**Comment by jbee** [comment]
Oh and coverage maybe is possible as part of sonar GH integration?

**Comment by sormuras** [comment]
Just edit/enhance/prune the initial comment.

**Comment by sormuras** [comment]
Updated initial description. Only 3 open tasks remaining.

**Comment by sormuras** [comment]
With the javadoc-related task tracked by #83, only the "Code Coverage" task is left.

**Comment by jbee** [comment]
Last item handled by #150
